INSERT INTO Pokemon(id, name, first_type, second_type, catch_rate, gender, caught) VALUES(20, 'Pikachu', 'Electric', '-', 190, 'Male', true)
INSERT INTO Pokemon(id, name, first_type, second_type, catch_rate, gender, caught) VALUES(31, 'Mewtwo', 'Psychic', '-', 3, 'Neutral', false)
INSERT INTO Pokemon(id, name, first_type, second_type, catch_rate, gender, caught) VALUES(42, 'Jolteon', 'Electric', '-', 45, 'Female', true)
INSERT INTO Pokemon(id, name, first_type, second_type, catch_rate, gender, caught) VALUES(55, 'Blastoise', 'Water', '-', 1, 'Female', false)
INSERT INTO Pokemon(id, name, first_type, second_type, catch_rate, gender, caught) VALUES(100, 'Swampert', 'Water', 'Ground', 255, 'Female', false)